# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GfJk56TpyOdpevXWD3rgiLrV8zBHt6o3
"""

import time
start_time = time.time()

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.utils.class_weight import compute_class_weight

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.layers import LSTM, TimeDistributed
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_csv("BEED_Data.csv")

# Son sütun LABEL varsayımı
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

print("X shape:", X.shape)
print("Sınıflar:", np.unique(y))

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)

class_weight_dict = dict(zip(np.unique(y_train), class_weights))
print("Class weights:", class_weight_dict)

"""🔵 MODEL 1 — CNN"""

X_train_cnn = X_train[..., np.newaxis]
X_test_cnn = X_test[..., np.newaxis]

num_classes = len(np.unique(y))

model_cnn = Sequential([
    Conv1D(32, 3, activation="relu", input_shape=(X_train_cnn.shape[1], 1)),
    MaxPooling1D(2),

    Conv1D(64, 3, activation="relu"),
    MaxPooling1D(2),

    Flatten(),
    Dense(64, activation="relu"),
    Dropout(0.5),

    Dense(num_classes, activation="softmax")
])

model_cnn.compile(
    optimizer=Adam(1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=7,
    restore_best_weights=True
)

model_cnn.fit(
    X_train_cnn,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=32,
    class_weight=class_weight_dict,
    callbacks=[early_stop],
    verbose=1
)

"""🟡 MODEL 2 — PCA + SVM"""

pca = PCA(n_components=0.95)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

svm = SVC(kernel="rbf", C=10, gamma="scale")
svm.fit(X_train_pca, y_train)

"""🟣 MODEL 3 — CNN-LSTM"""

TIMESTEPS = 5

def make_sequence(X, t):
    return np.array([np.tile(row, (t, 1)) for row in X])

X_train_seq = make_sequence(X_train, TIMESTEPS)[..., np.newaxis]
X_test_seq = make_sequence(X_test, TIMESTEPS)[..., np.newaxis]

model_cnn_lstm = Sequential([
    TimeDistributed(
        Conv1D(32, 3, activation="relu"),
        input_shape=(TIMESTEPS, X_train.shape[1], 1)
    ),
    TimeDistributed(MaxPooling1D(2)),
    TimeDistributed(Flatten()),

    LSTM(64),
    Dense(64, activation="relu"),
    Dense(num_classes, activation="softmax")
])

model_cnn_lstm.compile(
    optimizer=Adam(1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model_cnn_lstm.fit(
    X_train_seq,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=32,
    class_weight=class_weight_dict,
    callbacks=[early_stop],
    verbose=1
)

"""🔁 TÜM TEST VERİLERİ – TEK TEK KARŞILAŞTIRMA"""

results = []

for i in range(len(X_test)):
    true_label = y_test[i]

    # CNN
    pred_cnn = np.argmax(
        model_cnn.predict(X_test[i][np.newaxis, ..., np.newaxis], verbose=0)
    )

    # PCA + SVM
    pred_svm = svm.predict(pca.transform(X_test[i].reshape(1, -1)))[0]

    # CNN-LSTM
    seq = np.tile(X_test[i], (TIMESTEPS, 1))
    seq = seq[np.newaxis, ..., np.newaxis]
    pred_lstm = np.argmax(
        model_cnn_lstm.predict(seq, verbose=0)
    )

    results.append([
        i,
        true_label,
        pred_cnn,
        pred_svm,
        pred_lstm,
        int(pred_cnn == true_label),
        int(pred_svm == true_label),
        int(pred_lstm == true_label)
    ])

df_results = pd.DataFrame(
    results,
    columns=[
        "Test Index",
        "Gerçek Label",
        "CNN Tahmin",
        "PCA+SVM Tahmin",
        "CNN-LSTM Tahmin",
        "CNN Doğru",
        "SVM Doğru",
        "LSTM Doğru"
    ]
)

df_results

print("CNN Accuracy     :", df_results["CNN Doğru"].mean())
print("PCA+SVM Accuracy :", df_results["SVM Doğru"].mean())
print("CNN-LSTM Accuracy:", df_results["LSTM Doğru"].mean())

df_results.to_csv("BEED_test_sonuclari.csv", index=False)

end_time = time.time()
total_time = end_time - start_time

print(f"Toplam çalışma süresi: {total_time:.2f} saniye")
print(f"Dakika cinsinden: {total_time/60:.2f} dakika")

# ================== CONFUSION MATRIX (CNN-LSTM) ==================

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# 1) CNN-LSTM modelinden tahmin al
y_pred_probs = model_cnn_lstm.predict(X_test_seq)

# 2) Olasılıkları sınıf etiketine çevir
y_pred = np.argmax(y_pred_probs, axis=1)

# 3) Gerçek etiketler
# Eğer y_test one-hot değilse (sende öyle):
y_true = y_test

# 4) Confusion matrix hesapla
cm = confusion_matrix(y_true, y_pred)

# 5) Çizdir (rapora uygun)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[f"Class {i}" for i in range(len(np.unique(y_true)))]
)

disp.plot(cmap="Blues", values_format="d")
plt.title("CNN-LSTM Confusion Matrix")
plt.tight_layout()
plt.show()

# ================================================================